// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH0HtGflt2N-q_jUh2hvcpD5a4u5v3sVs',
    appId: '1:609639647992:web:aba0a829d473d273be890d',
    messagingSenderId: '609639647992',
    projectId: 'task-manager-8bcd8',
    authDomain: 'task-manager-8bcd8.firebaseapp.com',
    storageBucket: 'task-manager-8bcd8.appspot.com',
    measurementId: 'G-G5VPVG5355',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiqnOC6UhXhw4d1wR2BfMaBD6w4q8Gpak',
    appId: '1:609639647992:android:031774dee0acfd49be890d',
    messagingSenderId: '609639647992',
    projectId: 'task-manager-8bcd8',
    storageBucket: 'task-manager-8bcd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTlxKhfW8rIRCM20cslC62WR5fdu3_SmQ',
    appId: '1:609639647992:ios:2404326af24cf3c0be890d',
    messagingSenderId: '609639647992',
    projectId: 'task-manager-8bcd8',
    storageBucket: 'task-manager-8bcd8.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );
}
